In [1]:
import numpy as np

In [14]:
matrix = np.random.random((3, 4))
matrix

array([[0.54198125, 0.21129515, 0.02404119, 0.58025687],
       [0.98889012, 0.78174686, 0.81051509, 0.29864391],
       [0.7372922 , 0.77147063, 0.39129164, 0.91561241]])

In [15]:
matrix = matrix.transpose()
matrix

array([[0.54198125, 0.98889012, 0.7372922 ],
       [0.21129515, 0.78174686, 0.77147063],
       [0.02404119, 0.81051509, 0.39129164],
       [0.58025687, 0.29864391, 0.91561241]])

In [16]:
matrix = matrix.reshape(2, 6)
matrix

array([[0.54198125, 0.98889012, 0.7372922 , 0.21129515, 0.78174686,
        0.77147063],
       [0.02404119, 0.81051509, 0.39129164, 0.58025687, 0.29864391,
        0.91561241]])

In [17]:
matrix.sum(axis=1)

array([4.03267621, 3.0203611 ])

In [46]:
matrix[matrix < 0.5]

array([0.21129515, 0.02404119, 0.39129164, 0.29864391])

In [41]:
matrix20 = np.linspace(3,5,20)
matrix20

array([3.        , 3.10526316, 3.21052632, 3.31578947, 3.42105263,
       3.52631579, 3.63157895, 3.73684211, 3.84210526, 3.94736842,
       4.05263158, 4.15789474, 4.26315789, 4.36842105, 4.47368421,
       4.57894737, 4.68421053, 4.78947368, 4.89473684, 5.        ])

In [51]:
import pandas as pd

In [54]:
lista = [1,2,3,4,5,6,7,8]
serie = pd.Series(lista) 
serie

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [56]:
diccionario = {'A':['key1','key2'], 'B':[1,2],'C':[3,4]}
dt = pd.DataFrame(diccionario)
dt

A  B  C
0  key1  1  3
1  key2  2  4

In [58]:
dt.count()

A    2
B    2
C    2
dtype: int64

In [59]:
dt.columns

Index(['A', 'B', 'C'], dtype='object')

In [60]:
dt.index

RangeIndex(start=0, stop=2, step=1)

In [61]:
dt.describe()

B         C
count  2.000000  2.000000
mean   1.500000  3.500000
std    0.707107  0.707107
min    1.000000  3.000000
25%    1.250000  3.250000
50%    1.500000  3.500000
75%    1.750000  3.750000
max    2.000000  4.000000

In [62]:
dt['D'] = dt['B'] + dt['C']
dt

A  B  C  D
0  key1  1  3  4
1  key2  2  4  6